name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.REPO_TOKEN }}
          user: voidrot
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: America/Denver
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming, data
          plugin_languages_colors: github
          plugin_languages_details: percentage
          # plugin_languages_indepth: yes
          plugin_languages_limit: 10
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming, data
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # plugin_repositories: yes
          # plugin_repositories_order: featured, pinned, starred, random
